解决打开时出错的问题

diff --git a/root/usr/bin/wrapped-browser b/root/usr/bin/wrapped-browser
--- a/root/usr/bin/wrapped-browser
+++ b/root/usr/bin/wrapped-browser
@@ -2,9 +2,9 @@
 
 BIN=/usr/bin/poxenstudio-mybrowser-stable
 
-# Cleanup
-if pgrep mybrowser > /dev/null;then
-  rm -f $HOME/.config/mybrowser/Singleton*
+# Cleanup stale singleton lock left over from an unclean container shutdown
+if ! pgrep -f "${BIN}" > /dev/null; then
+  rm -f /data/mybrowser/Singleton*
 fi
 
 # Wayland check
